apiVersion: v1
kind: ResourceQuota
metadata:
  name: weather-quota
  namespace: weather
spec:
  hard:
    requests.cpu: "250m"
    requests.memory: "640Mi"
    limits.cpu: "600m"
    limits.memory: "1280Mi"