apiVersion: v1
kind: ResourceQuota
metadata:
  name: weather-quota
  namespace: weather
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: "512Mi"
    limits.cpu: "500m"
    limits.memory: "1024Mi"