apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: weather-ingress
  namespace: weather
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # For Traefik (K3s default)
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    # For automatic HTTPS redirect
    traefik.ingress.kubernetes.io/redirect-entry-point: websecure
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - weather.vivekpadayattil.com
    secretName: weather-tls-cert 
  rules:
  - host: weather.vivekpadayattil.com
    http:
      paths:
      - backend:
          service:
            name: weather-frontend-svc
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
