
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests to backend
    location /save {
        proxy_pass http://weather-api-svc:8080/save;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /delete/ {
        proxy_pass http://weather-api-svc:8080/delete/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
    location /health {
        proxy_pass http://weather-api-svc:8080/health;
    }
}

