apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-api-depl
  name: weather-api-depl
  namespace: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api-depl
  strategy: {}
  template:
    metadata:
      labels:
        app: weather-api-depl
    spec:
      containers:
        - image: vivupadi/weather-backend:latest
          imagePullPolicy: Always
          name: weather-backend
          resources: 
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
          volumeMounts:
          - name: weather-db
            mountPath: /app/db
      volumes:
      - name: weather-db
        persistentVolumeClaim:
          claimName: weather-db-pvc
status: {}
