apiVersion: batch/v1
kind: CronJob
metadata:
  name: message-user
  namespace: weather
spec:
  jobTemplate:
    metadata:
      name: message-user
    spec:
      template:
        metadata: {}
        spec:
          containers:
          - image: vivupadi/weather-cronjob:latest
            name: message-user
            resources: 
              requests:
                cpu: "50m"
                memory: "128Mi"
              limits:
                cpu: "150m"
                memory: "256Mi"
            volumeMounts:
            - name: weather-db
              mountPath: /app/db
            env:
            - name: weather_api_key
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: weather_api_key
            - name: gmail_id
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: gmail_id
            - name: google_app_password
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: google_app_password
          volumes:
          - name: weather-db
            persistentVolumeClaim:
              claimName: weather-db-pvc
          restartPolicy: OnFailure
  schedule: '45 * * * *'
status: {}
