apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-cron-depl
  name: weather-cron-depl
  namespace: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-cron-depl
  strategy: {}
  template:
    metadata:
      labels:
        app: weather-cron-depl
    spec:
      containers:
      - image: vivupadi/weather-cronjob:latest
        name: weather-cronjob
        resources: {}
status: {}
