apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-frontend-dpl
  name: weather-frontend-dpl
  namespace: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-frontend-dpl
  strategy: {}
  template:
    metadata:
      labels:
        app: weather-frontend-dpl
    spec:
      containers:
      - image: vivupadi/weather-frontend:latest
        name: weather-frontend
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
status: {}